//! Emits an asset manifest (`assets.rs`) into `OUT_DIR` that
//! `include_bytes!`-embeds every file in `frontend/dist`, so the
//! production server is a single static binary with no web-root
//! dependency (DESIGN §9, §15).
//!
//! If `frontend/dist` does not exist (a dev build without the
//! frontend), the manifest is empty and the server serves a
//! "frontend not built" placeholder for non-API paths.

use std::path::{Path, PathBuf};
use std::process::Command;

/// Compute a stable content hash for a file without pulling in a
/// crate (build-time; a simple FNV-1a over the bytes is plenty).
fn fnv1a(bytes: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in bytes {
        h ^= *b as u64;
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
}

fn guess_mime(path: &Path) -> &'static str {
    match path.extension().and_then(|e| e.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("webp") => "image/webp",
        Some("ico") => "image/x-icon",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("map") => "application/json",
        Some("wasm") => "application/wasm",
        _ => "application/octet-stream",
    }
}

/// Format a unix timestamp as `YYYY-MM-DD` (no date crate at build
/// time; the standard civil-from-days algorithm).
fn build_date() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0) as i64;
    let z = secs / 86_400 + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!("{y:04}-{m:02}-{d:02}")
}

fn main() {
    println!("cargo:rustc-env=BUILD_TIME={}", build_date());
    let dist = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("frontend")
        .join("dist");

    // Rebuild when the manifest or the dist root changes.
    println!("cargo:rerun-if-changed=build.rs");
    if dist.exists() {
        println!("cargo:rerun-if-changed={}", dist.display());
    }

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let manifest = out.join("assets.rs");

    let mut entries = Vec::new();
    if dist.is_dir() {
        walk(&dist, &dist, &mut entries);
    }
    entries.sort();

    let mut rs = "// Generated by build.rs — do not edit.\n\
                 #[allow(dead_code)]\n\
                 pub struct Asset {\n"
        .to_string();
    rs.push_str("    pub path: &'static str,\n");
    rs.push_str("    pub mime: &'static str,\n");
    rs.push_str("    pub bytes: &'static [u8],\n");
    rs.push_str("    pub hash: u64,\n");
    rs.push_str("}\n\n");
    rs.push_str("#[allow(dead_code)]\npub static ASSETS: &[Asset] = &[\n");
    for (rel, abs) in &entries {
        let bytes = std::fs::read(abs).unwrap_or_default();
        let hash = fnv1a(&bytes);
        // include_bytes! needs a path relative to the source file;
        // OUT_DIR is not under the crate, so copy the file into
        // OUT_DIR and reference it there (stable name = 16-hex hash).
        let name = format!("asset_{:016x}.bin", hash);
        let dest = out.join(&name);
        if !dest.exists() {
            std::fs::copy(abs, &dest).expect("copy asset");
        }
        rs.push_str(&format!(
            "    Asset {{ path: {rel:?}, mime: {mime:?}, bytes: include_bytes!(\"{name}\"), hash: {hash}, }},\n",
            mime = guess_mime(abs),
        ));
    }
    rs.push_str("];\n");

    std::fs::write(&manifest, rs).expect("write assets.rs");
    println!(
        "cargo:warning=embedded {} frontend asset(s) from {}",
        entries.len(),
        dist.display()
    );
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in rd.flatten() {
        let p = entry.path();
        if p.is_dir() {
            walk(root, &p, out);
        } else {
            let rel = p
                .strip_prefix(root)
                .expect("inside root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, p));
        }
    }
}

#[allow(dead_code)]
#[doc(hidden)]
fn _unused_command() {
    // Kept so the dep on `Command` doesn't warn during build-script
    // refactorings.
    let _ = Command::new("true");
}
